name: Release Build and Test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  SOURCE_DIRECTORY: source
  BUILD_DIRECTORY: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ${{env.SOURCE_DIRECTORY}}
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2
      with:
        modules: qtcharts
        setup-python: false
    - name: Configure the Project
      run: >
        cmake
        -S ${SOURCE_DIRECTORY}
        -B ${BUILD_DIRECTORY}
        -D CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=on
        -D CMAKE_BUILD_TYPE:STRING=Release
    - name: Build the Project
      run: cmake --build ${BUILD_DIRECTORY}
    - name: Run Unit Tests
      working-directory: ${{env.BUILD_DIRECTORY}}
      run: ctest --build-config Release --output-on-failure
