name: Debug Build and Test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]

env:
  BUILD_DIRECTORY: ../build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2
      with:
        modules: qtcharts
        setup-python: false
    - name: Install Tools
      run: sudo apt-get install lcov
    - name: Configure the Project
      run: >
        cmake
        -S .
        -B ${BUILD_DIRECTORY}
        -D CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=on
        -D CMAKE_BUILD_TYPE:STRING=Debug
    - name: Build the Project
      run: cmake --build ${BUILD_DIRECTORY}
    - name: Initialize Coverage Data
      run: lcov --capture --initial --directory ${BUILD_DIRECTORY} --output-file ../baseline.info
    - name: Run Unit Tests
      working-directory: ${{env.BUILD_DIRECTORY}}
      run: ctest --build-config Release --output-on-failure
    - name: Generate Coverage Data
      run: |
        lcov --capture --directory ${BUILD_DIRECTORY} --base-directory . --output-file ../coverage.info
        lcov --add-tracefile ../baseline.info --add-tracefile ../coverage.info --output-file ../combined.info
        lcov --remove ../combined.info '*Qt*' '*usr*' '*build*' --output-file ../final.info
    - name: Send Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: ../final.info
